export { Eksponensial } from './Eksponensial'
export { Trigonometri } from './Trigonometri'
export { Logaritma } from './Logaritma'
export { Rasional } from './Rasional'
export { Kuadrat } from './Kuadrat'
export { Linear } from './Linear'
