export const keywords: string[] = [
  // Keywords Utama
  'Trigonometri kalkulus',
  'Materi trigonometri',
  'Kalkulus trigonometri',
  'Fungsi trigonometri',
  'Grafik trigonometri',
  'Rumus trigonometri',
  'Sin cos tan',
  'Aplikasi trigonometri',
  'Trigonometri dasar',
  'Trigonometri lanjutan',

  // Keywords Spesifik
  'Amplitudo trigonometri',
  'Periode fungsi trigonometri',
  'Perubahan fase trigonometri',
  'Grafik sinus dan kosinus',
  'Fungsi sudut dalam kalkulus',
  'Transformasi fungsi trigonometri',
  'Kalkulator trigonometri online',
  'Derivatif fungsi trigonometri',
  'Integral fungsi trigonometri',
  'Pembelajaran trigonometri interaktif',

  // Keywords Long-tail
  'Cara menggambar grafik trigonometri',
  'Penjelasan fungsi sinus dan kosinus',
  'Hubungan trigonometri dengan kalkulus',
  'Contoh soal trigonometri dalam kalkulus',
  'Cara menghitung amplitudo dan periode',
  'Materi trigonometri untuk siswa SMA dan mahasiswa',
  'Grafik fungsi trigonometri menggunakan GeoGebra',
  'Rumus transformasi fungsi trigonometri lengkap',
  'Perbedaan sinus, kosinus, dan tangen',
  'Panduan belajar trigonometri online',

  //!   From Website
  'buku kalkulus widowati',
  'buku kalkulus yang bagus',
  'calculus based physics',
  'calculus basics',
  'calculus bc',
  'calculus bc curriculum',
  'calculus bc vs ab',
  'calculus book',
  'calculus bridge',
  'calculus bridge images',
  'calculus buildup',
  'calculus by james stewart',
  'calculus calculator',
  'calculus calculator with steps',
  'calculus cd',
  'calculus chain rule',
  'calculus cheat sheet',
  'calculus cholecystitis',
  'calculus circle',
  'calculus class',
  'calculus concepts',
  'calculus continuity',
  'calculus grade 3',
  'calculus howard anton',
  'calculus name origin',
  'calculus newton',
  "calculus newton's method",
  'calculus normal line',
  'calculus notation',
  'calculus notebook',
  'calculus notes',
  'calculus notes pdf',
  'calculus noun',
  'calculus numerical graphical algebraic pdf',
  'calculus of kidney',
  'calculus reddit',
  'calculus renal',
  'calculus renalis',
  'diskusi 5 kalkulus 1',
  'diskusi 5 kalkulus 1 ut',
  'diskusi 5 kalkulus ut',
  'diskusi 6 kalkulus 1 ut',
  'diskusi 7 kalkulus',
  'diskusi 7 kalkulus ut',
  'diskusi 8 kalkulus',
  'diskusi 8 kalkulus 1',
  'diskusi 8 kalkulus 1 ut',
  'diskusi 8 kalkulus ut',
  'fasit kalkulus og lineær algebra',
  'icd x kalkulus',
  'icd x kalkulus gigi',
  'is 64 6',
  'kalkulus 1',
  'kalkulus 1 itb',
  'kalkulus 1 limit',
  'kalkulus 1 pdf',
  'kalkulus 1 pdf download',
  'kalkulus 1 purcell',
  'kalkulus 1 purcell pdf',
  'kalkulus 1 teknik elektro',
  'kalkulus 1 ui',
  'kalkulus 1 ut',
  'kalkulus 1 warsito',
  'kalkulus 2',
  'kalkulus 2 itb',
  'kalkulus 2 purcell pdf',
  'kalkulus 2 teknik elektro',
  'kalkulus 2 teknik industri',
  'kalkulus 2 teknik informatika',
  'kalkulus 2 tentang apa',
  'kalkulus 2 ui',
  'kalkulus 2a',
  'kalkulus 2c',
  'kalkulus 3',
  'kalkulus 3 adalah',
  'kalkulus 3 itb',
  'kalkulus 3 pdf',
  'kalkulus 3 teknik industri',
  'kalkulus 3 teknik sipil',
  'kalkulus 3 uit',
  'kalkulus 3 ut',
  'kalkulus 3 utgave',
  'kalkulus 3d',
  'kalkulus 4 adalah',
  'kalkulus 4 pdf',
  'kalkulus 4 udgave',
  'kalkulus 4 utgave',
  'kalkulus 4 utgave pdf',
  'kalkulus ada berapa',
  'kalkulus ada di jurusan apa',
  'kalkulus adalah',
  'kalkulus adalah jurnal',
  'kalkulus ai',
  'kalkulus aljabar',
  'kalkulus apa',
  'kalkulus apa saja',
  'kalkulus apparel',
  'kalkulus artinya',
  'kalkulus dan geometri analitis jilid 1',
  'kalkulus dan geometri analitis jilid 1 pdf',
  'kalkulus dan geometri analitis pdf',
  'kalkulus dasar',
  'kalkulus dasar pdf',
  'kalkulus dasar untuk perguruan tinggi',
  'kalkulus dental',
  'kalkulus diferensial',
  'kalkulus diferensial adalah',
  'kalkulus diferensial pdf',
  'kalkulus diskusi 4',
  'kalkulus diskusi 5',
  'kalkulus diskusi 6',
  'kalkulus ebook',
  'kalkulus edisi 5',
  'kalkulus edisi 5 jilid 1',
  'kalkulus edisi 8',
  'kalkulus edisi 8 jilid 1',
  'kalkulus edisi 9 jilid 1 pdf',
  'kalkulus edisi 9 jilid 2 pdf',
  'kalkulus ekonomi',
  'kalkulus elementer',
  'kalkulus erlangga',
  'kalkulus farmasi',
  'kalkulus fisika',
  'kalkulus fungsi trigonometri',
  'kalkulus fungsi invers',
  'kalkulus gigi adalah',
  'kalkulus ginjal adalah',
  'kalkulus lanjut pdf',
  'kalkulus limit fungsi aljabar',
  'kalkulus materi',
  'kalkulus multivariabel',
  'kalkulus og lineær algebra',
  'kalkulus online',
  'kalkulus pdf',
  'kalkulus purcell',
  'kalkulus trigonometri',
  'kalkulus vektor',
  'kalkulus untuk perguruan tinggi',
  'kalkulus wikipedia',
  'fungsi trigonometri kelas 12',
  'rumus fungsi trigonometri',
  'fungsi trigonometri kelas 11',
  'fungsi trigonometri adalah',
]
